name: Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
      - name: Install tytanic
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tytanic
          git: https://github.com/tingerrr/tytanic.git
      - run: |
          rustup target add wasm32-unknown-unknown
          CETZ=$(mktemp -d)
          mkdir -p ~/.local/share/typst/packages/preview/cetz
          git clone --depth 1 --branch release-0.4.0 https://github.com/cetz-package/cetz.git "$CETZ"
          cd "$CETZ"
          git submodule update --init --recursive
          just install @preview
      - uses: typst-community/setup-typst@v3
        with:
          typst-version: '0.13.1'
          cache-dependency-path: src/cetz.typ
      - run: |
          just install @local
          just install @preview
          just manual
          just test
